# Generated by Django 4.1.3 on 2022-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAudio', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Estado',
            new_name='EstadoAlarma',
        ),
        migrations.RenameField(
            model_name='estadoalarma',
            old_name='estado',
            new_name='estadoAlarma',
        ),
        migrations.RenameField(
            model_name='motivoalarma',
            old_name='tipo',
            new_name='motivoAlarma',
        ),
        migrations.RenameField(
            model_name='motivoaudio',
            old_name='tipo',
            new_name='motivoAudio',
        ),
        migrations.RenameField(
            model_name='productoalarmas',
            old_name='alarmas',
            new_name='productoAlarmas',
        ),
        migrations.RenameField(
            model_name='productoaudio',
            old_name='audio',
            new_name='productoAudio',
        ),
    ]
