# Generated by Django 4.1.3 on 2022-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='mail',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
